[dev]
 autoLaunch = false

[build]
command = "npm run mock-server"
functions = "netlify/functions"

[[headers]]
for = "/*"
[headers.values]
Access-Control-Allow-Origin = "*"
Content-Type = "application/json"
